### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by pjwalmsley** [lkcampbell/brackets-ruler#43] opened 2015-05-01 13:45 UTC
I've tried installing with all three methods.  I'm on build 1.3.0-16022.  
![capture](https://cloud.githubusercontent.com/assets/3832357/7430899/c33464e6-efe6-11e4-9ea7-f706f2b70824.PNG)

**Comment by lkcampbell** [comment] 2015-05-04 13:57
@pjwalmsley, is this just happening for this specific extension or for all extensions because I'm not able to reproduce the problem.

**Comment by pjwalmsley** [comment] 2015-05-04 16:40
It was specific to this extension Friday.  Today it appears no extensions will install (I'm now getting some node errors - perhaps related to project size).  

Re-installing brackets seemed to do the trick.  Sorry to waste your time and thanks for this useful extension!

I'm seeing another issue where attempting to grab (to adjust) the guide on the ruler shifts it 6 chars to the left.  Resizing works fine; the ruler just isn't aligned with my pointer.

**Comment by lkcampbell** [comment] 2015-05-05 01:17
Is the problem similar to https://github.com/lkcampbell/brackets-ruler/issues/41?

If not, could you open up an issue with repro steps? I'm not able to reproduce the problem.

**Comment by lkcampbell** [comment] 2015-06-07 14:43
Haven't received a response back. Closing as fixed since the original bug was a core code problem with the extension manager.

**Closed by lkcampbell** 2015-06-07 14:43 UTC
Labels: invalid

**Comment by glepretre** [comment] 2015-06-08 07:42
I had this error message once, in my case in was due to another extension (brackets-JSCS).

There is an opened issue in brackets repo: https://github.com/adobe/brackets/issues/9723

**Comment by chris-chalmers** [comment] 2015-06-08 23:12
I get this issue on all extensions. I just installed brackets for the first time and all attempts at installing extensions show the same error: "Installation failed. Unknown internal error". I'm on mac OS 10.9.5 I've got virtualbox installed and have used vagrant for projects in the past, as well as mamp but none of those VMS or servers are running now. Here's the content of my hosts file: 
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1:8080  localhost
255.255.255.255 broadcasthost
::1             localhost
fe80::1%lo0     localhost

127.0.0.1 activate.adobe.com
127.0.0.1 practivate.adobe.com
127.0.0.1 ereg.adobe.com
127.0.0.1 activate.wip3.adobe.com
127.0.0.1 wip3.adobe.com
127.0.0.1 3dns-3.adobe.com
127.0.0.1 3dns-2.adobe.com
127.0.0.1 adobe-dns.adobe.com
127.0.0.1 adobe-dns-2.adobe.com
127.0.0.1 adobe-dns-3.adobe.com
127.0.0.1 ereg.wip3.adobe.com
127.0.0.1 activate-sea.adobe.com
127.0.0.1 wwis-dubc1-vip60.adobe.com
127.0.0.1 activate-sjc0.adobe.com

#Added by XAMPP Control
127.0.0.1 chris-chalmerss-macbook-pro.local

I also tried after deleting all the adobe-generated lines in there, same result. 

Thanks in advance!
